### ISSUE TITLE
Drop support for PHP versions 7.1, 7.2 and 7.3

### ISSUE THREAD

**Issue by slunak** [slunak/pushover-php#15]
I will be dropping support for PHP versions `7.1`, `7.2` and `7.3`, making version `7.4` a minimal required version to run this library. The library version number will be incremented from `1.2.0` to `2.0.0`. I will then stop supporting the version `1.2.0`.

Update: After dropping mentioned PHP versions, the library minor version will be incremented, e.g. `1.3.0`.

**Comment by OskarStark** [comment]
Makes sense, but dropping a php version can be done in a minor, no major needed

**Comment by slunak** [comment]
Hm... Dropping php version will break backwards compatibility. When this is the case, then major version should be incremented. Do you mind pointing to some examples @OskarStark where what you suggest was done please?

**Comment by OskarStark** [comment]
From a library point of view, if you release 1.3.0 with `>=7.4` you are unable to install 1.4.0, because you need to perform some manual changes to your code (upgrade to PHP 7.4), but you cannot accidentally install 1.3.0 because your local PHP version is blocking this. So your code will still work, but with `1.2.0`. To upgrade to `2.0.0` you would need to perform the same steps.

IMHO it's more blocking the adoption of all users out there, already using newer PHP versions, which should be the "happy path".

Does that makes sense to you? Btw. even dropping a dependency is no BC break, if your application for example depends on a lib venor/package, this is required by your lib, you are responsible to declare a requirement in your own `composer.json` file.

I am currently on the go and have no repos in mind, but IIRC we do this @sonata-project like this, am I right @VincentLanglet?

**Comment by VincentLanglet** [comment]
Dropping a PHP version can be done in a minor version. We already did multiple times for sonata indeed @OskarStark.

But if you drop the php version and add typehint, it might require a BC-break.
We used a major version when dropping 7.4 because it allows us to type everything.

**Comment by OskarStark** [comment]
> But if you drop the php version and add typehint, it might require a BC-break.
> We used a major version when dropping 7.4 because it allows us to type everything.

Yes, but technically would be correct to drop the version in a minor, deprecate things etc. and then create a new major without the deprecations.

But yes, if you plan to add types and modernize the codebase, it should be done in a new major.

Hope this helps 👍

**Comment by slunak** [comment]
Absolutely, thanks @OskarStark and @VincentLanglet
